In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler
import os

In [4]:
folder = './ProcessedBases'
base_dir = 'ProcessedBases'
bases = [name for name in os.listdir(folder) if os.path.isdir(os.path.join(folder, name))]
scaler = StandardScaler()
reduced = ['Letter-2', 'Isolet', 'Page-blocks', 'Nursery']

for basename in bases:
    df = pd.read_csv('{0}/{1}/{2}.csv'.format(folder,basename, basename.lower()), header=None)   
    
    
    y = df.iloc[:,-1:]
    X = df.iloc[:, :-1]
    
    scaled_features = StandardScaler().fit_transform(X.values)
    X = pd.DataFrame(scaled_features, index=X.index, columns=X.columns)
    
    skf = StratifiedKFold(n_splits=5)
    
    if (basename in reduced):
        print(basename)
        print(len(X))
        skf_reduced = StratifiedKFold(n_splits=10)
        for train_index, test_index in skf_reduced.split(X, y):        
            X_red = X.iloc[test_index]
            y_red = y.iloc[test_index]
            break
        X = X_red
        y = y_red 

        df = X.join(y)
        df.to_csv('{0}/{1}/{2}.csv'.format(base_dir,basename,basename.lower()), index = False, header=False)
        print("new len", len(X))
    
    fold = 1
    mylist = y
    #print(np.unique(y)) 
    primeiro_label = np.unique(y)[0]

    if(primeiro_label == 0):
        y += 1
    print(np.unique(y)) 

    for train_index, test_index in skf.split(X, y):        
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]
        df_train = X_train.join(y_train)
        df_test = X_test.join(y_test)

        df_train.to_csv('{0}/{1}/{2}_{3}_train.csv'.format(base_dir,basename, basename.lower(),fold), index = False, header=False)
        df_test.to_csv('{0}/{1}/{2}_{3}_test.csv'.format(base_dir,basename, basename.lower(),fold), index = False, header=False)

        fold = fold + 1
        
        

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]
[1 2 3 4 5 6]
[1 2 3 4]
[1 2 3 4 5]


C:\Users\leona\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6]


C:\Users\leona\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[1 2 3 5 6 7]
Isolet
7797
new len 780
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26.]
[ 1  2  3  4  5  6  7  8  9 10]
Letter-2
20000
new len 2000
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


C:\Users\leona\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\leona\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[1 2 3 4]
Nursery
12960
new len 1296
[1 2 3 4 5]
Page-blocks

C:\Users\leona\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\leona\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=10.
  warnings.warn(("The least populated class in y has only %d"
C:\Users\leona\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"



5472
new len 548
[1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]


C:\Users\leona\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[1 2 3 4 5 7]
[1 2 3 4 5 6 7]
[1 2 3 4 5]


C:\Users\leona\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"


[1 2 3 4]
[ 1  2  3  4  5  6  7  8  9 10 11]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7]


C:\Users\leona\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(("The least populated class in y has only %d"
